"""Generate shared/billing-cases.json: one case set checked by pytest AND vitest.

The hand-written vectors are the independent truth of the billing rule; the random cases are
produced by the backend implementation (the source of truth for money) and pin its behaviour,
so that a change of the rounding rule on either side fails a test instead of drifting apart.
Run from backend/:  PYTHONPATH=. uv run python scripts/generate_shared_cases.py
"""

import json
import random
from decimal import Decimal
from pathlib import Path

from app.billing import Segment, SegmentKind, bill, segment_cost
from app.geo import Point, point_in_polygon
from app.zones import BISHKEK_CENTER_ZONE

OUT = Path(__file__).resolve().parents[2] / "shared" / "billing-cases.json"
SEED = 20260912

# rate, seconds, expected — the vectors that were duplicated in both suites until now
HAND_VECTORS: list[tuple[str, int, str]] = [
    ("5.00", 0, "0.00"),
    ("5.00", 1, "0.08"),
    ("5.00", 59, "4.92"),
    ("5.00", 60, "5.00"),
    ("5.00", 61, "5.08"),
    ("5.00", 90, "7.50"),
    ("5.00", 119, "9.92"),
    ("5.00", 120, "10.00"),
    ("1.50", 1, "0.03"),
    ("1.50", 30, "0.75"),
    ("7.50", 1, "0.13"),
    ("0.01", 1, "0.00"),
    ("0.01", 30, "0.01"),
    ("1.50", 11, "0.28"),
    ("2.45", 30, "1.23"),
    ("1.15", 30, "0.58"),
    ("0.29", 60, "0.29"),
]


def money(value: Decimal) -> str:
    return str(value.quantize(Decimal("0.01")))


def main() -> None:
    rng = random.Random(SEED)
    for rate, seconds, expected in HAND_VECTORS:
        assert money(segment_cost(Decimal(rate), seconds)) == expected, (rate, seconds)

    segment_costs = [
        {"rate": rate, "seconds": seconds, "cost": expected}
        for rate, seconds, expected in HAND_VECTORS
    ]
    # random rates as 2-decimal strings, random durations; a quarter of them are exact ties
    for _ in range(400):
        seconds = rng.randint(0, 7200)
        if rng.random() < 0.25:
            # a tie: rate_kopecks * seconds ≡ 30 (mod 60) -> odd seconds with a rate of x.50-ish
            seconds = rng.randrange(1, 7200, 2)
            rate = Decimal(rng.choice([150, 450, 750, 1050, 2550])) / 100
        else:
            rate = Decimal(rng.randint(1, 99_999)) / 100
        segment_costs.append(
            {"rate": money(rate), "seconds": seconds, "cost": money(segment_cost(rate, seconds))}
        )

    rides = []
    for _ in range(150):
        ride_rate = Decimal(rng.randint(1, 5000)) / 100
        pause_rate = Decimal(rng.randint(1, 2000)) / 100
        segments = [
            Segment(rng.choice(list(SegmentKind)), rng.randint(0, 1800))
            for _ in range(rng.randint(1, 12))
        ]
        receipt = bill(segments, ride_rate, pause_rate)
        rides.append(
            {
                "ride_rate": money(ride_rate),
                "pause_rate": money(pause_rate),
                "segments": [{"kind": s.kind.value, "seconds": s.seconds} for s in segments],
                "expected": {
                    "ride_seconds": receipt.ride_seconds,
                    "pause_seconds": receipt.pause_seconds,
                    "ride_cost": money(receipt.ride_cost),
                    "pause_cost": money(receipt.pause_cost),
                    "total_cost": money(receipt.total_cost),
                },
            }
        )

    zone = list(BISHKEK_CENTER_ZONE.points)
    zone_cases: list[dict[str, object]] = [
        {"lat": 42.8756, "lon": 74.6036, "inside": True, "note": "Ala-Too Square"},
        {"lat": 42.8747, "lon": 74.5731, "inside": False, "note": "Osh Bazaar"},
        {"lat": 42.9300, "lon": 74.6000, "inside": False, "note": "far north"},
        {"lat": 42.8500, "lon": 74.6000, "inside": False, "note": "south of the railway"},
    ]
    for index, vertex in enumerate(zone):
        nxt = zone[(index + 1) % len(zone)]
        zone_cases.append(
            {"lat": vertex.lat, "lon": vertex.lon, "inside": True, "note": f"vertex {index}"}
        )
        # the exact midpoint of the edge: on the boundary, hence inside by the rule
        mid = Point((vertex.lat + nxt.lat) / 2, (vertex.lon + nxt.lon) / 2)
        zone_cases.append(
            {"lat": mid.lat, "lon": mid.lon, "inside": True, "note": f"midpoint of edge {index}"}
        )
    for _ in range(200):
        lat = round(rng.uniform(42.850, 42.900), 6)
        lon = round(rng.uniform(74.560, 74.640), 6)
        zone_cases.append(
            {"lat": lat, "lon": lon, "inside": point_in_polygon(Point(lat, lon), zone)}
        )
    for case in zone_cases:
        assert (
            point_in_polygon(Point(float(case["lat"]), float(case["lon"])), zone) is case["inside"]
        ), case

    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(
        json.dumps(
            {
                "$comment": (
                    "Generated by backend/scripts/generate_shared_cases.py, do not edit by hand. "
                    "Checked by backend/tests/test_shared_cases.py "
                    "and frontend/src/ride/sharedCases.test.ts."
                ),
                "seed": SEED,
                "segment_costs": segment_costs,
                "rides": rides,
                "zone": {
                    "name": BISHKEK_CENTER_ZONE.name,
                    "points": [{"lat": p.lat, "lon": p.lon} for p in zone],
                    "cases": zone_cases,
                },
            },
            ensure_ascii=False,
            indent=1,
        )
        + "\n",
        encoding="utf-8",
        newline="\n",
    )
    print(
        f"wrote {OUT}: {len(segment_costs)} segment costs, {len(rides)} rides, "
        f"{len(zone_cases)} zone points"
    )


if __name__ == "__main__":
    main()
