/**
 * Parity with the backend on the shared case set (shared/billing-cases.json), generated by
 * backend/scripts/generate_shared_cases.py and checked by backend/tests/test_shared_cases.py.
 * The TypeScript billing and point-in-polygon mirrors must agree with the backend on every case.
 */
import { readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { describe, expect, it } from 'vitest'

import type { ZonePoint } from '../api/types'
import { formatMoney, parseMoney, segmentCostKopecks } from './billing'
import { pointInPolygon } from './geo'

interface SegmentCase {
  rate: string
  seconds: number
  cost: string
}

interface RideCase {
  ride_rate: string
  pause_rate: string
  segments: Array<{ kind: 'ride' | 'pause'; seconds: number }>
  expected: {
    ride_seconds: number
    pause_seconds: number
    ride_cost: string
    pause_cost: string
    total_cost: string
  }
}

interface SharedCases {
  segment_costs: SegmentCase[]
  rides: RideCase[]
  zone: { name: string; points: ZonePoint[]; cases: Array<ZonePoint & { inside: boolean; note?: string }> }
}

const here = dirname(fileURLToPath(import.meta.url))
const CASES = JSON.parse(
  readFileSync(resolve(here, '../../../shared/billing-cases.json'), 'utf8'),
) as SharedCases

describe('shared billing cases (parity with the backend)', () => {
  it('is a substantial set', () => {
    expect(CASES.segment_costs.length).toBeGreaterThanOrEqual(400)
    expect(CASES.rides.length).toBeGreaterThanOrEqual(100)
  })

  it('prices every segment exactly like the backend', () => {
    const mismatches = CASES.segment_costs.filter(
      (c) => formatMoney(segmentCostKopecks(parseMoney(c.rate), c.seconds)) !== c.cost,
    )
    expect(mismatches).toEqual([])
  })

  it('sums every ride exactly like the backend', () => {
    const mismatches = CASES.rides.filter((ride) => {
      const rideRate = parseMoney(ride.ride_rate)
      const pauseRate = parseMoney(ride.pause_rate)
      let rideSeconds = 0
      let pauseSeconds = 0
      let rideKopecks = 0
      let pauseKopecks = 0
      for (const segment of ride.segments) {
        if (segment.kind === 'ride') {
          rideSeconds += segment.seconds
          rideKopecks += segmentCostKopecks(rideRate, segment.seconds)
        } else {
          pauseSeconds += segment.seconds
          pauseKopecks += segmentCostKopecks(pauseRate, segment.seconds)
        }
      }
      const e = ride.expected
      return (
        rideSeconds !== e.ride_seconds ||
        pauseSeconds !== e.pause_seconds ||
        formatMoney(rideKopecks) !== e.ride_cost ||
        formatMoney(pauseKopecks) !== e.pause_cost ||
        formatMoney(rideKopecks + pauseKopecks) !== e.total_cost
      )
    })
    expect(mismatches).toEqual([])
  })
})

describe('shared zone cases (parity with the backend point-in-polygon)', () => {
  it('classifies every point, boundary points included, exactly like the backend', () => {
    const mismatches = CASES.zone.cases.filter(
      (c) => pointInPolygon({ lat: c.lat, lon: c.lon }, CASES.zone.points) !== c.inside,
    )
    expect(mismatches).toEqual([])
  })
})
